CREATE TABLE IF NOT EXISTS import_export_batch (
    id                    BIGINT       NOT NULL PRIMARY KEY COMMENT '主键',
    batch_no              VARCHAR(64)  NOT NULL COMMENT '批次号',
    type                  VARCHAR(32)  NOT NULL COMMENT '批次类型 import/export',
    file_name             VARCHAR(255)          DEFAULT NULL COMMENT '文件名',
    operator_id           BIGINT                DEFAULT NULL COMMENT '操作人ID',
    operate_time          DATETIME              DEFAULT NULL COMMENT '操作时间',
    total                 INT          NOT NULL DEFAULT 0 COMMENT '总数',
    success_count         INT          NOT NULL DEFAULT 0 COMMENT '成功数',
    fail_count            INT          NOT NULL DEFAULT 0 COMMENT '失败数',
    error_report_file_id  BIGINT                DEFAULT NULL COMMENT '异常报告文件ID',
    scope_json            JSON                  DEFAULT NULL COMMENT '范围/筛选条件',
    preview_json          JSON                  DEFAULT NULL COMMENT '预校验成功行JSON',
    strategy              VARCHAR(32)           DEFAULT NULL COMMENT '导入策略',
    status                VARCHAR(32)  NOT NULL DEFAULT 'PREVALIDATED' COMMENT '状态 PREVALIDATED/IMPORTED/ROLLED_BACK/PARTIAL_ROLLBACK/FAILED/EXPORTED',
    remark                VARCHAR(500)          DEFAULT NULL COMMENT '备注',
    created_by            BIGINT                DEFAULT NULL COMMENT '创建人',
    created_at            DATETIME              DEFAULT NULL COMMENT '创建时间',
    updated_by            BIGINT                DEFAULT NULL COMMENT '更新人',
    updated_at            DATETIME              DEFAULT NULL COMMENT '更新时间',
    deleted               TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除 0正常1删除',
    UNIQUE KEY uk_import_export_batch_no (batch_no, deleted),
    KEY idx_import_export_batch_type (type),
    KEY idx_import_export_batch_status (status),
    KEY idx_import_export_batch_time (operate_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '导入导出批次';

CREATE TABLE IF NOT EXISTS import_error_detail (
    id              BIGINT       NOT NULL PRIMARY KEY COMMENT '主键',
    batch_id        BIGINT       NOT NULL COMMENT '批次ID',
    batch_no        VARCHAR(64)  NOT NULL COMMENT '批次号',
    row_no          INT          NOT NULL COMMENT 'Excel行号',
    student_no      VARCHAR(64)           DEFAULT NULL COMMENT '学号',
    student_name    VARCHAR(64)           DEFAULT NULL COMMENT '姓名',
    field_name      VARCHAR(128) NOT NULL COMMENT '字段',
    error_value     VARCHAR(512)          DEFAULT NULL COMMENT '错误值',
    error_reason    VARCHAR(512) NOT NULL COMMENT '错误原因',
    suggestion      VARCHAR(512)          DEFAULT NULL COMMENT '建议处理方式',
    created_by      BIGINT                DEFAULT NULL COMMENT '创建人',
    created_at      DATETIME              DEFAULT NULL COMMENT '创建时间',
    updated_by      BIGINT                DEFAULT NULL COMMENT '更新人',
    updated_at      DATETIME              DEFAULT NULL COMMENT '更新时间',
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除 0正常1删除',
    KEY idx_import_error_batch (batch_id),
    KEY idx_import_error_batch_no (batch_no),
    KEY idx_import_error_row (row_no)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '导入异常明细';

CREATE TABLE IF NOT EXISTS import_record_ref (
    id              BIGINT       NOT NULL PRIMARY KEY COMMENT '主键',
    batch_id        BIGINT       NOT NULL COMMENT '批次ID',
    batch_no        VARCHAR(64)  NOT NULL COMMENT '批次号',
    table_name      VARCHAR(64)  NOT NULL COMMENT '表名',
    record_id       BIGINT       NOT NULL COMMENT '记录ID',
    action          VARCHAR(32)  NOT NULL COMMENT '动作 INSERT/UPDATE/SKIP/CONFLICT',
    before_json     JSON                  DEFAULT NULL COMMENT '导入前快照',
    after_json      JSON                  DEFAULT NULL COMMENT '导入后快照，用于回滚冲突判定',
    row_no          INT                   DEFAULT NULL COMMENT 'Excel行号',
    remark          VARCHAR(500)          DEFAULT NULL COMMENT '备注',
    created_by      BIGINT                DEFAULT NULL COMMENT '创建人',
    created_at      DATETIME              DEFAULT NULL COMMENT '创建时间',
    updated_by      BIGINT                DEFAULT NULL COMMENT '更新人',
    updated_at      DATETIME              DEFAULT NULL COMMENT '更新时间',
    deleted         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除 0正常1删除',
    KEY idx_import_ref_batch (batch_id),
    KEY idx_import_ref_batch_no (batch_no),
    KEY idx_import_ref_record (table_name, record_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '导入记录回滚追溯';
