export const STATUS_LABELS: Record<string, string> = {
  DRAFT: '草稿',
  WAIT_SUBMIT: '待提交',
  FIRST_REVIEW: '待初审',
  FIRST_REJECTED: '初审退回',
  SECOND_REVIEW: '待复审',
  SECOND_REJECTED: '复审退回',
  PASSED: '已通过',
  FAILED: '不合格',
  PASS: '通过',
  REJECT: '退回',
  FAIL: '不通过',
  LOCKED: '已锁定',
  NORMAL: '正常',
  CONFIRMED: '已确认',
  RETURNED: '已退回',
  WAIT_UPLOAD: '待上传',
  VALIDATING: '校验中',
  VALIDATION_FAILED: '校验未通过',
  WAIT_REVIEW: '待评审',
  REVIEWING: '评审中',
  NEED_REVIEW: '需复评',
  REVIEW_COMPLETED: '评审完成',
  GENERATED: '已生成',
  ISSUED: '已签发',
  EXPORTED: '已导出',
  ARCHIVED: '已归档',
  VOIDED: '已作废',
  REISSUED: '已重开',
  COMPLETED: '已完成',
  RUNNING: '运行中',
  PENDING: '待处理',
  FAILED_TASK: '失败',
  ENABLED: '启用',
  DISABLED: '停用',
  UNREAD: '未读',
  READ: '已读',
  IMPORTED: '导入成功',
  IMPORTING: '导入中',
  PREVALIDATED: '预校验通过',
  ROLLED_BACK: '已回滚',
  INSERT: '新增',
  UPDATE: '更新',
  DELETE: '删除',
  SUCCESS: '成功',
  ERROR: '失败',
  WARNING: '警告',
  INFO: '提示'
}

export const OPERATION_LABELS: Record<string, string> = {
  save: '保存',
  create: '新增',
  update: '更新',
  submit: '提交',
  firstReview: '初审',
  secondReview: '复审',
  confirm: '确认',
  return: '退回',
  reject: '退回',
  fail: '不通过',
  assign: '指派',
  score: '评分',
  generate: '生成',
  issue: '签发',
  export: '导出',
  import: '导入',
  archive: '归档',
  void: '作废',
  reissue: '重开',
  correct: '更正',
  rollback: '回滚',
  login: '登录',
  delete: '删除',
  backup: '备份',
  trigger: '触发',
  read: '已读',
  markRead: '标记已读',
  'student:create': '新增学生',
  'student:update': '更新学生',
  'student:submit': '提交学生信息',
  'student:firstReview': '学生信息初审',
  'student:secondReview': '学生信息复审',
  'training:create': '新增培养信息',
  'training:update': '更新培养信息',
  'training:submit': '提交培养信息',
  'training:firstReview': '培养信息初审',
  'training:secondReview': '培养信息复审',
  'material:submit': '提交材料',
  'material:firstReview': '材料初审',
  'material:secondReview': '材料复审',
  'exemption:submit': '提交免考申请',
  'exemption:firstReview': '免考初审',
  'exemption:secondReview': '免考复审',
  'video:assign': '视频指派',
  'video:score': '视频评分',
  'video:arbitrate': '视频仲裁',
  'video:confirm': '视频确认',
  'cert:generate': '证书生成',
  'cert:issue': '证书签发',
  'cert:void': '证书作废',
  'cert:reissue': '证书重开',
  'cert:correct': '证书更正',
  'exchange:import': '导入',
  'exchange:export': '导出',
  'exchange:rollback': '导入回滚'
}

export function statusLabel(code?: string | null) {
  if (!code) return '-'
  return STATUS_LABELS[code] || code
}

export function operationLabel(code?: string | null) {
  if (!code) return '-'
  return OPERATION_LABELS[code] || code
}
