<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.edu.gpnu</groupId>
        <artifactId>teacher-cert-platform</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>platform-business</artifactId>
    <description>业务：学生、培养、材料、免考、视频、测试、证书（后续充实）</description>

    <dependencies>
        <dependency>
            <groupId>cn.edu.gpnu</groupId>
            <artifactId>platform-common</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.edu.gpnu</groupId>
            <artifactId>platform-system</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.edu.gpnu</groupId>
            <artifactId>platform-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>
</project>
