import type { GlobalThemeOverrides } from 'naive-ui'

const fontFamily = '-apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", "PingFang SC", Roboto, Helvetica, Arial, sans-serif'
const monoFamily = '"JetBrains Mono", ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#1d4ed8',
    primaryColorHover: '#1e40af',
    primaryColorPressed: '#1e3a8a',
    primaryColorSuppl: '#2563eb',
    infoColor: '#2563eb',
    infoColorHover: '#1d4ed8',
    infoColorPressed: '#1e40af',
    infoColorSuppl: '#3b82f6',
    successColor: '#16a34a',
    successColorHover: '#15803d',
    successColorPressed: '#166534',
    successColorSuppl: '#22c55e',
    warningColor: '#d97706',
    warningColorHover: '#b45309',
    warningColorPressed: '#92400e',
    warningColorSuppl: '#f59e0b',
    errorColor: '#dc2626',
    errorColorHover: '#b91c1c',
    errorColorPressed: '#991b1b',
    errorColorSuppl: '#ef4444',
    bodyColor: '#f6f8fb',
    baseColor: '#ffffff',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    tableHeaderColor: '#f8fafc',
    tableColorHover: '#eff4ff',
    tableColorStriped: '#fbfdff',
    hoverColor: '#eff4ff',
    pressedColor: '#dbeafe',
    dividerColor: '#e5e7eb',
    borderColor: '#e5e7eb',
    textColor1: '#0f172a',
    textColor2: '#475569',
    textColor3: '#94a3b8',
    textColorDisabled: '#94a3b8',
    placeholderColor: '#94a3b8',
    placeholderColorDisabled: '#cbd5e1',
    inputColor: '#ffffff',
    inputColorDisabled: '#f8fafc',
    railColor: '#e5e7eb',
    fontFamily,
    fontFamilyMono: monoFamily,
    fontWeight: '400',
    fontWeightStrong: '600',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontSize: '14px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '20px',
    lineHeight: '1.55',
    heightSmall: '32px',
    heightMedium: '34px',
    heightLarge: '40px',
    cubicBezierEaseInOut: 'cubic-bezier(.4, 0, .2, 1)',
    cubicBezierEaseOut: 'cubic-bezier(0, 0, .2, 1)',
    cubicBezierEaseIn: 'cubic-bezier(.4, 0, 1, 1)'
  },
  Button: {
    heightTiny: '24px',
    heightSmall: '32px',
    heightMedium: '34px',
    heightLarge: '40px',
    borderRadiusTiny: '4px',
    borderRadiusSmall: '6px',
    borderRadiusMedium: '6px',
    borderRadiusLarge: '6px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    paddingTiny: '0 8px',
    paddingSmall: '0 12px',
    paddingMedium: '0 14px',
    paddingLarge: '0 16px',
    colorSecondary: '#f8fafc',
    colorSecondaryHover: '#eff4ff',
    colorSecondaryPressed: '#dbeafe',
    colorQuaternary: 'transparent',
    colorQuaternaryHover: '#eff4ff',
    colorQuaternaryPressed: '#dbeafe',
    textColorText: '#475569',
    textColorTextHover: '#1d4ed8',
    textColorTextPressed: '#1e40af',
    border: '1px solid #d1d5db',
    borderHover: '1px solid #1d4ed8',
    borderPressed: '1px solid #1e40af',
    borderFocus: '1px solid #1d4ed8',
    rippleColor: '#1d4ed8'
  },
  DataTable: {
    borderRadius: '8px',
    lineHeight: '1.55',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    thColor: '#f8fafc',
    thColorHover: '#f8fafc',
    thColorSorting: '#f1f5f9',
    thTextColor: '#475569',
    thFontWeight: '500',
    tdColor: '#ffffff',
    tdColorHover: '#eff4ff',
    tdColorStriped: '#fbfdff',
    tdColorSorting: '#ffffff',
    tdTextColor: '#0f172a',
    borderColor: '#e5e7eb',
    thPaddingSmall: '10px 12px',
    thPaddingMedium: '11px 12px',
    tdPaddingSmall: '10px 12px',
    tdPaddingMedium: '11px 12px',
    paginationMargin: '14px 0 0 auto',
    emptyPadding: '36px 0'
  },
  Menu: {
    color: '#ffffff',
    borderRadius: '6px',
    fontSize: '14px',
    itemHeight: '38px',
    groupTextColor: '#94a3b8',
    itemTextColor: '#475569',
    itemTextColorHover: '#1d4ed8',
    itemTextColorActive: '#1d4ed8',
    itemTextColorActiveHover: '#1d4ed8',
    itemTextColorChildActive: '#1d4ed8',
    itemTextColorChildActiveHover: '#1d4ed8',
    itemIconColor: '#64748b',
    itemIconColorHover: '#1d4ed8',
    itemIconColorActive: '#1d4ed8',
    itemIconColorActiveHover: '#1d4ed8',
    itemColorHover: '#f8fafc',
    itemColorActive: '#eff4ff',
    itemColorActiveHover: '#eff4ff',
    itemColorActiveCollapsed: '#eff4ff',
    arrowColor: '#94a3b8',
    arrowColorHover: '#1d4ed8',
    arrowColorActive: '#1d4ed8',
    dividerColor: '#e5e7eb'
  },
  Tag: {
    borderRadius: '4px',
    fontSizeSmall: '12px',
    heightSmall: '24px',
    fontWeightStrong: '500',
    color: '#f8fafc',
    textColor: '#475569',
    border: '1px solid #e5e7eb',
    colorPrimary: '#eff4ff',
    textColorPrimary: '#1d4ed8',
    borderPrimary: '1px solid #bfdbfe',
    colorInfo: '#eff6ff',
    textColorInfo: '#2563eb',
    borderInfo: '1px solid #bfdbfe',
    colorSuccess: '#ecfdf3',
    textColorSuccess: '#16a34a',
    borderSuccess: '1px solid #bbf7d0',
    colorWarning: '#fffbeb',
    textColorWarning: '#d97706',
    borderWarning: '1px solid #fed7aa',
    colorError: '#fef2f2',
    textColorError: '#dc2626',
    borderError: '1px solid #fecaca',
    padding: '0 8px'
  },
  Card: {
    color: '#ffffff',
    textColor: '#0f172a',
    titleTextColor: '#0f172a',
    borderColor: '#e5e7eb',
    borderRadius: '8px',
    boxShadow: '0 1px 2px rgba(16, 24, 40, .04), 0 1px 3px rgba(16, 24, 40, .06)',
    paddingSmall: '16px 18px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontSizeSmall: '15px',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '18px',
    titleFontWeight: '600'
  },
  Input: {
    heightSmall: '32px',
    heightMedium: '34px',
    heightLarge: '40px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    borderRadius: '6px',
    color: '#ffffff',
    colorDisabled: '#f8fafc',
    colorFocus: '#ffffff',
    textColor: '#0f172a',
    textColorDisabled: '#64748b',
    placeholderColor: '#94a3b8',
    placeholderColorDisabled: '#cbd5e1',
    border: '1px solid #d1d5db',
    borderHover: '1px solid #1d4ed8',
    borderFocus: '1px solid #1d4ed8',
    borderDisabled: '1px solid #e5e7eb',
    boxShadowFocus: '0 0 0 2px rgba(29, 78, 216, .14)',
    paddingSmall: '0 10px',
    paddingMedium: '0 10px',
    paddingLarge: '0 12px'
  },
  Form: {
    labelTextColor: '#475569',
    labelFontWeight: '500',
    labelFontSizeTopSmall: '13px',
    labelFontSizeTopMedium: '13px',
    labelFontSizeTopLarge: '14px',
    labelHeightSmall: '20px',
    labelHeightMedium: '20px',
    labelHeightLarge: '22px',
    labelPaddingVertical: '0 0 6px 0',
    feedbackFontSizeSmall: '12px',
    feedbackFontSizeMedium: '12px',
    feedbackPadding: '4px 0 0 0',
    asteriskColor: '#dc2626'
  },
  Select: {
    peers: {
      InternalSelection: {
        heightSmall: '32px',
        heightMedium: '34px',
        heightLarge: '40px',
        borderRadius: '6px',
        color: '#ffffff',
        colorDisabled: '#f8fafc',
        colorActive: '#ffffff',
        border: '1px solid #d1d5db',
        borderHover: '1px solid #1d4ed8',
        borderActive: '1px solid #1d4ed8',
        borderFocus: '1px solid #1d4ed8',
        boxShadowActive: '0 0 0 2px rgba(29, 78, 216, .14)',
        boxShadowFocus: '0 0 0 2px rgba(29, 78, 216, .14)',
        textColor: '#0f172a',
        textColorDisabled: '#64748b',
        placeholderColor: '#94a3b8',
        fontSizeSmall: '13px',
        fontSizeMedium: '14px'
      },
      InternalSelectMenu: {
        color: '#ffffff',
        borderRadius: '8px',
        optionHeightSmall: '32px',
        optionHeightMedium: '34px',
        optionFontSizeSmall: '13px',
        optionFontSizeMedium: '14px',
        optionColorPending: '#eff4ff',
        optionColorActive: '#eff4ff',
        optionTextColorActive: '#1d4ed8',
        optionCheckColor: '#1d4ed8'
      }
    }
  },
  Pagination: {
    itemSizeSmall: '30px',
    itemSizeMedium: '32px',
    itemBorderRadius: '6px',
    itemTextColor: '#475569',
    itemTextColorHover: '#1d4ed8',
    itemTextColorActive: '#1d4ed8',
    itemColor: '#ffffff',
    itemColorHover: '#eff4ff',
    itemColorActive: '#eff4ff',
    itemBorder: '1px solid #e5e7eb',
    itemBorderHover: '1px solid #bfdbfe',
    itemBorderActive: '1px solid #1d4ed8'
  },
  Empty: {
    textColor: '#64748b',
    iconColor: '#94a3b8',
    extraTextColor: '#475569',
    fontSizeMedium: '13px',
    iconSizeMedium: '44px'
  }
}

