import type { GlobalThemeOverrides } from 'naive-ui'

const fontFamily = '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", Inter, Roboto, sans-serif'
const monoFamily = '"JetBrains Mono", ui-monospace, Consolas, "Liberation Mono", Menlo, monospace'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#0d9488',
    primaryColorHover: '#0f766e',
    primaryColorPressed: '#115e59',
    primaryColorSuppl: '#14b8a6',
    infoColor: '#0ea5e9',
    infoColorHover: '#0284c7',
    infoColorPressed: '#0369a1',
    infoColorSuppl: '#38bdf8',
    successColor: '#10b981',
    successColorHover: '#059669',
    successColorPressed: '#047857',
    successColorSuppl: '#34d399',
    warningColor: '#f59e0b',
    warningColorHover: '#d97706',
    warningColorPressed: '#b45309',
    warningColorSuppl: '#f59e0b',
    errorColor: '#ef4444',
    errorColorHover: '#dc2626',
    errorColorPressed: '#b91c1c',
    errorColorSuppl: '#f87171',
    bodyColor: '#f6f8f7',
    baseColor: '#ffffff',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    tableHeaderColor: '#f3faf8',
    tableColorHover: '#f0fdfa',
    tableColorStriped: '#fcfdfb',
    hoverColor: '#f0fdfa',
    pressedColor: '#ccfbf1',
    dividerColor: '#eef0ee',
    borderColor: '#eef0ee',
    textColor1: '#1f2937',
    textColor2: '#4b5563',
    textColor3: '#9ca3af',
    textColorDisabled: '#9ca3af',
    placeholderColor: '#9ca3af',
    placeholderColorDisabled: '#d1d5db',
    inputColor: '#ffffff',
    inputColorDisabled: '#fafbf9',
    railColor: '#eef0ee',
    fontFamily,
    fontFamilyMono: monoFamily,
    fontWeight: '400',
    fontWeightStrong: '600',
    borderRadius: '10px',
    borderRadiusSmall: '8px',
    fontSize: '14px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    fontSizeHuge: '20px',
    lineHeight: '1.55',
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '42px',
    cubicBezierEaseInOut: 'cubic-bezier(.4, 0, .2, 1)',
    cubicBezierEaseOut: 'cubic-bezier(0, 0, .2, 1)',
    cubicBezierEaseIn: 'cubic-bezier(.4, 0, 1, 1)'
  },
  Button: {
    heightTiny: '26px',
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '42px',
    borderRadiusTiny: '8px',
    borderRadiusSmall: '10px',
    borderRadiusMedium: '10px',
    borderRadiusLarge: '10px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    paddingTiny: '0 10px',
    paddingSmall: '0 14px',
    paddingMedium: '0 16px',
    paddingLarge: '0 18px',
    colorSecondary: '#fafbf9',
    colorSecondaryHover: '#f0fdfa',
    colorSecondaryPressed: '#ccfbf1',
    colorQuaternary: 'transparent',
    colorQuaternaryHover: '#f0fdfa',
    colorQuaternaryPressed: '#ccfbf1',
    textColorText: '#4b5563',
    textColorTextHover: '#0d9488',
    textColorTextPressed: '#0f766e',
    border: '1px solid #e2e6e3',
    borderHover: '1px solid #0d9488',
    borderPressed: '1px solid #0f766e',
    borderFocus: '1px solid #0d9488',
    rippleColor: '#0d9488'
  },
  DataTable: {
    borderRadius: '14px',
    lineHeight: '1.55',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    thColor: '#f3faf8',
    thColorHover: '#f3faf8',
    thColorSorting: '#e6f7f3',
    thTextColor: '#4b5563',
    thFontWeight: '500',
    tdColor: '#ffffff',
    tdColorHover: '#f0fdfa',
    tdColorStriped: '#fcfdfb',
    tdColorSorting: '#ffffff',
    tdTextColor: '#1f2937',
    borderColor: '#eef0ee',
    thPaddingSmall: '13px 16px',
    thPaddingMedium: '14px 16px',
    tdPaddingSmall: '13px 16px',
    tdPaddingMedium: '14px 16px',
    paginationMargin: '18px 0 0 auto',
    emptyPadding: '44px 0'
  },
  Menu: {
    color: '#ffffff',
    borderRadius: '10px',
    fontSize: '14px',
    itemHeight: '42px',
    groupTextColor: '#9ca3af',
    itemTextColor: '#4b5563',
    itemTextColorHover: '#0d9488',
    itemTextColorActive: '#0d9488',
    itemTextColorActiveHover: '#0d9488',
    itemTextColorChildActive: '#0d9488',
    itemTextColorChildActiveHover: '#0d9488',
    itemIconColor: '#6b7280',
    itemIconColorHover: '#0d9488',
    itemIconColorActive: '#0d9488',
    itemIconColorActiveHover: '#0d9488',
    itemColorHover: '#f0fdfa',
    itemColorActive: '#f0fdfa',
    itemColorActiveHover: '#f0fdfa',
    itemColorActiveCollapsed: '#f0fdfa',
    arrowColor: '#9ca3af',
    arrowColorHover: '#0d9488',
    arrowColorActive: '#0d9488',
    dividerColor: '#eef0ee'
  },
  Tag: {
    borderRadius: '999px',
    fontSizeSmall: '12px',
    heightSmall: '26px',
    fontWeightStrong: '500',
    color: '#fafbf9',
    textColor: '#4b5563',
    border: '1px solid #eef0ee',
    colorPrimary: '#f0fdfa',
    textColorPrimary: '#0d9488',
    borderPrimary: '1px solid #99f6e4',
    colorInfo: '#eff6ff',
    textColorInfo: '#0ea5e9',
    borderInfo: '1px solid #bae6fd',
    colorSuccess: '#ecfdf5',
    textColorSuccess: '#10b981',
    borderSuccess: '1px solid #a7f3d0',
    colorWarning: '#fffbeb',
    textColorWarning: '#f59e0b',
    borderWarning: '1px solid #fde68a',
    colorError: '#fef2f2',
    textColorError: '#ef4444',
    borderError: '1px solid #fecaca',
    padding: '0 10px'
  },
  Card: {
    color: '#ffffff',
    textColor: '#1f2937',
    titleTextColor: '#1f2937',
    borderColor: 'transparent',
    borderRadius: '14px',
    boxShadow: '0 1px 3px rgba(17, 24, 39, .06), 0 6px 16px rgba(17, 24, 39, .05)',
    paddingSmall: '20px',
    paddingMedium: '24px',
    paddingLarge: '28px',
    titleFontSizeSmall: '15px',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '18px',
    titleFontWeight: '600'
  },
  Input: {
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '42px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    borderRadius: '10px',
    color: '#ffffff',
    colorDisabled: '#fafbf9',
    colorFocus: '#ffffff',
    textColor: '#1f2937',
    textColorDisabled: '#6b7280',
    placeholderColor: '#9ca3af',
    placeholderColorDisabled: '#d1d5db',
    border: '1px solid #e2e6e3',
    borderHover: '1px solid #0d9488',
    borderFocus: '1px solid #0d9488',
    borderDisabled: '1px solid #eef0ee',
    boxShadowFocus: '0 0 0 2px rgba(13, 148, 136, .18)',
    paddingSmall: '0 12px',
    paddingMedium: '0 12px',
    paddingLarge: '0 14px'
  },
  Form: {
    labelTextColor: '#4b5563',
    labelFontWeight: '500',
    labelFontSizeTopSmall: '13px',
    labelFontSizeTopMedium: '13px',
    labelFontSizeTopLarge: '14px',
    labelHeightSmall: '20px',
    labelHeightMedium: '20px',
    labelHeightLarge: '22px',
    labelPaddingVertical: '0 0 8px 0',
    feedbackFontSizeSmall: '12px',
    feedbackFontSizeMedium: '12px',
    feedbackPadding: '5px 0 0 0',
    asteriskColor: '#ef4444'
  },
  Select: {
    peers: {
      InternalSelection: {
        heightSmall: '34px',
        heightMedium: '36px',
        heightLarge: '42px',
        borderRadius: '10px',
        color: '#ffffff',
        colorDisabled: '#fafbf9',
        colorActive: '#ffffff',
        border: '1px solid #e2e6e3',
        borderHover: '1px solid #0d9488',
        borderActive: '1px solid #0d9488',
        borderFocus: '1px solid #0d9488',
        boxShadowActive: '0 0 0 2px rgba(13, 148, 136, .18)',
        boxShadowFocus: '0 0 0 2px rgba(13, 148, 136, .18)',
        textColor: '#1f2937',
        textColorDisabled: '#6b7280',
        placeholderColor: '#9ca3af',
        fontSizeSmall: '13px',
        fontSizeMedium: '14px'
      },
      InternalSelectMenu: {
        color: '#ffffff',
        borderRadius: '14px',
        optionHeightSmall: '34px',
        optionHeightMedium: '36px',
        optionFontSizeSmall: '13px',
        optionFontSizeMedium: '14px',
        optionColorPending: '#f0fdfa',
        optionColorActive: '#f0fdfa',
        optionTextColorActive: '#0d9488',
        optionCheckColor: '#0d9488'
      }
    }
  },
  Pagination: {
    itemSizeSmall: '32px',
    itemSizeMedium: '34px',
    itemBorderRadius: '10px',
    itemTextColor: '#4b5563',
    itemTextColorHover: '#0d9488',
    itemTextColorActive: '#0d9488',
    itemColor: '#ffffff',
    itemColorHover: '#f0fdfa',
    itemColorActive: '#f0fdfa',
    itemBorder: '1px solid #eef0ee',
    itemBorderHover: '1px solid #99f6e4',
    itemBorderActive: '1px solid #0d9488'
  },
  Empty: {
    textColor: '#6b7280',
    iconColor: '#99f6e4',
    extraTextColor: '#4b5563',
    fontSizeMedium: '13px',
    iconSizeMedium: '48px'
  }
}
